In [33]:
#Loading the required libraries
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
#read the file
data=pd.read_csv("main_data.csv")

In [3]:
data

,url,title
0,https://www.flipkart.com/eyebogler-checkered-m...,Men Checkered Mandarin Collar Blue T-ShirtEyeB...
1,https://ajiobusiness.com/storefront/ProductDet...,Twill Checks Casual ShirtsNEVERDOWN
2,https://www.flipkart.com/pepzo-men-solid-casua...,Men Regular Fit Solid Spread Collar Casual Shi...
3,https://www.flipkart.com/reslag-men-washed-cas...,Men Regular Fit Washed Cut Away Collar Casual ...
4,https://ajiobusiness.com/storefront/ProductDet...,Linen Solid Formal ShirtsSouthbay
...,...,...
10642,https://trends.ajio.com/first-class-printed-sh...,Printed Shirt with Patch PocketFIRST CLASS
10643,https://www.flipkart.com/kajaru-striped-men-ro...,"Pack of 2 Men Striped Round Neck Pink, Black T..."
10644,https://ajiobusiness.com/storefront/ProductDet...,Twill Checks ShirtZORRO CASUALS
10645,https://ajiobusiness.com/storefront/ProductDet...,Cotton Checks Casual ShirtsWANWIRO
10646,https://trends.ajio.com/612-league-checked-shi...,Checked Shirt and T-shirt Set612 LEAGUE

In [4]:
new=[]
for i in data["title"]:
  i=re.sub('[\s+\d+:\.\)\( ]',' ',i) #'\.' spaces, numbers, colon, paranthesis, full stop rmoval
  i=re.sub(r'\S*@\S*\s?','',i)  # Email removal
  new.append(i)

data["title"]=new

In [6]:
data=data.drop_duplicates()
data=data.dropna(axis=0) #drop duplicates

In [7]:
data.isnull().sum()

url      0
title    0
dtype: int64

#Approach-1

In [8]:
##convert a words
tfidf=TfidfVectorizer()
mat= tfidf.fit_transform(data["title"])

In [9]:
df=pd.DataFrame(mat.todense(),columns=tfidf.get_feature_names_out())
df=pd.concat([pd.Series(data["url"]),df],axis=1)

In [10]:
df=df.dropna(axis=0)

In [11]:
df

,url,abstract,accentallen,accentencrustd,accentkazo,accentkraus,aditya,adv,air,all,...,women,womens,wood,woven,wrodss,xohy,yash,ydc,yellow,zip
0,https://www.flipkart.com/eyebogler-checkered-m...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,https://www.flipkart.com/pepzo-men-solid-casua...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,https://www.flipkart.com/reslag-men-washed-cas...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10162,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10163,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10164,https://www.flipkart.com/stylemodo-men-solid-c...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10165,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10166,https://ajiobusiness.com/storefront/ProductDet...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
def top_n_get_results(test,n):
    t1=tfidf.transform([test])
    sim1=cosine_similarity(np.asarray(t1.todense()),np.asarray(mat.todense())).reshape(-1)
    res=pd.concat([df["url"],pd.Series(sim1).rename("score")],axis=1)
    res=res.sort_values(by=["score"],ascending=False)[0:n]
    top_n=np.array(res["url"])
    results={"urls":top_n}
    return results
    
top_n_get_results("men black white shirt",5)

{'urls': array(['https://ajiobusiness.com/storefront/ProductDetails/464823549',
        'https://ajiobusiness.com/storefront/ProductDetails/464967534',
        'https://www.ajio.com/van-heusen-floral-print-cotton-shirt/p/469220672_white',
        'https://ajiobusiness.com/storefront/ProductDetails/464915301',
        'https://ajiobusiness.com/storefront/ProductDetails/464967073'],
       dtype=object)}

In [12]:
test="men black t-shirt"
t1=tfidf.transform([test])

In [13]:
sim1=cosine_similarity(np.asarray(t1.todense()),np.asarray(mat.todense()))
sim1

array([[0.09168584, 0.        , 0.095383  , ..., 0.27938144, 0.        ,
        0.        ]])

In [127]:
sim1=sim1.reshape(-1)
sim1

array([0.09168584, 0.        , 0.095383  , ..., 0.27938144, 0.        ,
       0.        ])

In [128]:
#cosine similarity and the score
res=pd.concat([df["url"],pd.Series(sim1).rename("score")],axis=1)
res=res.sort_values(by=["score"],ascending=False)[0:10]
res

                                                     url     score
1108   https://ajiobusiness.com/storefront/ProductDet...  0.532842
10017  https://ajiobusiness.com/storefront/ProductDet...  0.457153
2833   https://ajiobusiness.com/storefront/ProductDet...  0.439115
1424   https://ajiobusiness.com/storefront/ProductDet...  0.439115
3718   https://www.flipkart.com/hanumntra-men-printed...  0.438889
7953   https://ajiobusiness.com/storefront/ProductDet...  0.433018
4872   https://ajiobusiness.com/storefront/ProductDet...  0.433018
4406   https://ajiobusiness.com/storefront/ProductDet...  0.426747
6818   https://ajiobusiness.com/storefront/ProductDet...  0.421025
5218   https://ajiobusiness.com/storefront/ProductDet...  0.421025

#Using  Latent semantic indexing

In [24]:
tsvt=TruncatedSVD(n_components=2)

In [25]:
lsa=tsvt.fit_transform(mat)

In [148]:

## A better representation of the  above one
Data=pd.DataFrame(lsa,columns=['Topic1','Topic2'])
Data['Original']=data["title"]
Data["url"]=data["url"]
display(Data[["url",'Original',"Topic1","Topic2"]])

,url,Original,Topic1,Topic2
0,https://www.flipkart.com/eyebogler-checkered-m...,Men Checkered Mandarin Collar Blue T-ShirtEyeB...,0.060315,-0.154934
1,https://ajiobusiness.com/storefront/ProductDet...,Twill Checks Casual ShirtsNEVERDOWN,0.417651,-0.113553
2,https://www.flipkart.com/pepzo-men-solid-casua...,Men Regular Fit Solid Spread Collar Casual Shi...,0.203772,-0.305035
3,https://www.flipkart.com/reslag-men-washed-cas...,Men Regular Fit Washed Cut Away Collar Casual ...,0.153093,-0.271228
4,https://ajiobusiness.com/storefront/ProductDet...,Linen Solid Formal ShirtsSouthbay,0.087774,-0.079900
...,...,...,...,...
10162,https://ajiobusiness.com/storefront/ProductDet...,Cotton Checks Casual ShirtsROYAL JACK FASHION LAB,0.615309,0.674397
10163,https://ajiobusiness.com/storefront/ProductDet...,Cotton Printed ShirtSHEVRON,0.065733,-0.041128
10164,https://www.flipkart.com/stylemodo-men-solid-c...,Men Slim Fit Solid Slim Collar Casual ShirtSty...,0.033804,-0.096447
10165,https://ajiobusiness.com/storefront/ProductDet...,Cotton Printed Shirt KKA,0.120459,-0.002955
10166,https://ajiobusiness.com/storefront/ProductDet...,Cotton Checks ShirtDUALITY,0.388954,-0.142145

In [149]:
dictionary=tfidf.get_feature_names_out()
dictionary

array(['abstract', 'accentallen', 'accentencrustd', ..., 'ydc', 'yellow',
       'zip'], dtype=object)

In [150]:
print(tsvt.components_)
print(tsvt.components_.shape)

[[ 3.96857057e-04  8.13813187e-06  2.90462308e-05 ...  8.68510801e-06
   3.92336533e-03  1.84335790e-04]
 [-3.87992527e-04 -2.97808883e-05 -7.46467883e-05 ... -3.30289968e-05
  -9.34197683e-03 -5.53669510e-04]]
(2, 1258)

In [151]:
encoding_matrix=pd.DataFrame(tsvt.components_,index=['Topic1','Topic2'],columns=dictionary).T
encoding_matrix

                  Topic1    Topic2
abstract        0.000397 -0.000388
accentallen     0.000008 -0.000030
accentencrustd  0.000029 -0.000075
accentkazo      0.000007 -0.000023
accentkraus     0.000020 -0.000080
...                  ...       ...
xohy            0.000033 -0.000103
yash            0.015333 -0.008457
ydc             0.000009 -0.000033
yellow          0.003923 -0.009342
zip             0.000184 -0.000554

[1258 rows x 2 columns]

In [181]:
query_vec= tsvt.transform(t1)
doc_trans= np.dot(mat.todense(),tsvt.components_.T)

In [153]:

doc_trans.shape

(10167, 2)

In [154]:
from sklearn.metrics.pairwise import cosine_similarity

In [155]:
sim=cosine_similarity(np.asarray(query_vec),np.asarray(doc_trans))

In [156]:
sim=sim.reshape(-1)
sim

array([0.99975772, 0.61210924, 0.98091399, ..., 0.99842428, 0.40573189,
       0.67696544])

In [174]:
res=pd.concat([Data["url"],pd.Series(sim).rename("score")],axis=1)
res=res.sort_values(by=["score"],ascending=False)[0:10]
top_n=np.array(res["url"])
res={"urls":top_n}

In [175]:
#Top_n results out
res={"urls":top_n}
res

{'urls': array(['https://www.flipkart.com/cazzba-men-checkered-casual-maroon-black-shirt/p/itm32c626d7d4b8c?pid=SHTGZYQZKW2XKN8C&lid=LSTSHTGZYQZKW2XKN8CP0UYHN&marketplace=FLIPKART&store=clo%2Fash%2Faxc%2Fmmk%2Fkp7&srno=b_17_661&otracker=browse&fm=organic&iid=en_QmqBn5703iLoHxPGRIGH%2FweHeBzxR7Wug9krFF%2FSY3%2BswZ1%2FCrq9Bz%2BCh6Qt2EvtWU%2FxDNR%2F5o9ax%2BF%2Bqc%2B6dg%3D%3D&ppt=None&ppn=None&ssid=tyh73jdrw00000001684591901400',
        'https://ajiobusiness.com/storefront/ProductDetails/464956465',
        nan,
        'https://ajiobusiness.com/storefront/ProductDetails/464755738',
        'https://ajiobusiness.com/storefront/ProductDetails/469234177',
        'https://ajiobusiness.com/storefront/ProductDetails/464712634',
        'https://ajiobusiness.com/storefront/ProductDetails/464877358',
        'https://ajiobusiness.com/storefront/ProductDetails/464591596',
        'https://ajiobusiness.com/storefront/ProductDetails/464804171',
        'https://ajiobusiness.com/storefront/ProductDetails/464714035'],
       dtype=object)}